server.port=8081

razorpay.key.id=rzp_test_SxRyHDYwsoD3c5
razorpay.key.secret=A91oeI1WGrC8W6moBXW4Bkhn

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update